[package]
name = "raffle-platform-contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }