apiVersion: apps/v1
kind: Deployment
metadata:
  name: raffle-backend
  namespace: raffle-platform
  labels:
    app: raffle-backend
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: raffle-backend
  template:
    metadata:
      labels:
        app: raffle-backend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: raffle-backend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: raffle-backend
        image: raffleplatform/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: RUST_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: jwt-secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: stripe-webhook-secret
        - name: BLOCKCHAIN_RPC_URL
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: blockchain-rpc-url
        - name: CONTRACT_ADDRESS
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: contract-address
        - name: DEPLOYER_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: deployer-private-key
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: raffle-secrets
              key: sentry-dsn
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: logs
        emptyDir: {}
      - name: uploads
        persistentVolumeClaim:
          claimName: raffle-uploads-pvc
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - raffle-backend
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: raffle-backend-service
  namespace: raffle-platform
  labels:
    app: raffle-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: raffle-backend

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raffle-backend
  namespace: raffle-platform

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: raffle-backend-pdb
  namespace: raffle-platform
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: raffle-backend